# Use an image with GCC installed
FROM gcc:latest

# Set the working directory in the container
WORKDIR /app/worker

# Copy all files from the current directory to the workdir in the container
COPY . .